blank_issues_enables: false
contact_links:
  - name: 질문은 Discussions에서!
    url: "https://github.com/prgrms-web-devcourse-final-project/WEB5_6_MOCI_FE/discussions"
    about: 질문이나 일반적인 논의는 Discussions 탭을 이용해주세요.
