import type { Metadata } from "next";
import "./globals.css";
import SmoothScrollerProvider from "@/provider/SmoothScrollerProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body>
        <SmoothScrollerProvider>{children}</SmoothScrollerProvider>
      </body>
    </html>
  );
}
